
- name: Stop sendmail server
  service: name=sendmail state=stopped enabled=no

- name: Install apache server
  yum: name={{ item }} state=present
  with_items:
    - httpd

- name: Install php
  yum: name={{ item }} state=present
  with_items:
    - php
    - php-mysql
    - php-gd
    - php-xml
    - php-mbstring

- name: Download and unarchive drupal
  unarchive: src=http://ftp.drupal.org/files/projects/drupal-7.8.tar.gz dest=/var/www/html remote_src=yes

- name: Download and unarchive drupal
  unarchive: src=http://ftp.drupal.org/files/projects/drush-7.x-4.5.tar.gz dest=/tmp remote_src=yes

- name: Create sql for create database
  file: path=/tmp/setup.mysql content="CREATE DATABASE IF NOT EXISTS drupaldb;" owner=root group=root mode=0644

- name: Run init sql script.
  shell: mysql -u root --password={{ mysql_root_password }} < /tmp/setup.mysql

- name: Add cfg mgmt user to sudoers
  #lineinfile: dest=/etc/httpd/conf/httpd.conf regexp='AllowOverride None' line='{{ item.line }}' state=present
  command: sed -i 's/AllowOverride None/AllowOverride All/g' /etc/httpd/conf/httpd.conf

- name: Start httpd server
  service: name=httpd state=started enabled=yes

- name: Run init sql script. # Todo change this line properly
  shell: /tmp/drush/drush site-install standard --yes --site-name='Example Site' --account-name=admin --account-pass=admin --db-url=mysql://root:{{ mysql_root_password }}@localhost/drupaldb --db-prefix=drupal_
  args:
    chdir: /var/www/html

- name: Chown /var/www/html/sites/default/files
  file: path=/var/www/html/sites/default/files owner=apache group=apache

